### ISSUE TITLE
Design a homepage

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/marvelUniverse#4]
Design a home page for the app! Kindly use react-router module and make three url
1. / Home page 
2. /Characters the actual search place
In home page kindly leave it blank but make sure /characters work!

**Comment by dev-sankhadip** [comment]
Can i go ahead in this?

**Comment by sudipt1999** [comment]
Sure!

**Comment by AmanR28** [comment]
I m on it.
