### ISSUE TITLE
Make a page for all Marvel's comics to search just like we have for characters!

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/marvelUniverse#5]
Kindly add a page for all marvels movie to be searched, you can the already present components from the app or you can design you own!
If you design your own make a issue for it first!

**Comment by himanshu272** [comment]
I would like to contribute to this issue. 
Before contributing, I would like to make a separate component to search for the movies. Should I make a new issue for it first here or in my cloned repo?

**Comment by sudipt1999** [comment]
Sure go ahead!

**Comment by sudipt1999** [comment]
Make issue here only!

**Comment by sudipt1999** [comment]
@himanshu272 kindly check this out! No movies so we are moving with comics https://developer.marvel.com/docs

**Comment by himanshu272** [comment]
I found an API which could provide the details of any movie. I thought that could do the job and started working on it. It's called OMDb API. @sudipt1999

**Comment by sudipt1999** [comment]
But we need only Marvel's if it's possible you can go ahead with it and make pr !

**Comment by himanshu272** [comment]
Okay, I'll move with comics.

**Comment by sudipt1999** [comment]
Great! Let's work on it!
