### ISSUE TITLE
Improve the footer

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/marvelUniverse#6]
Make footer more recognizable and intimidating!

**Comment by dev-sankhadip** [comment]
I would like to work on this issue, how should i proceed to contribute?

**Comment by dev-sankhadip** [comment]
Can we have some communication?

**Comment by AmanR28** [comment]
Can I work on it?

**Comment by sudipt1999** [comment]
sure go ahead

**Comment by AmanR28** [comment]
#7 Here it is.

**Comment by AmanR28** [comment]
#14

**Comment by AmanR28** [comment]
Here it is.
PR : #14
