### ISSUE TITLE
Improve character card ui

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/marvelUniverse#7]
Improve the character card ui and it's animation to make it more nice!

**Comment by puspaul** [comment]
I would like to contribute in improving the character card ui

**Comment by puspaul** [comment]
is there no communication channel for this project ??do we have to report any issue or ask any query by coming here?

**Comment by sudipt1999** [comment]
You can join gitter for the njack! And if there are any queries you can ask in comment here only.

**Comment by AmanR28** [comment]
Can I work on it?

**Comment by sudipt1999** [comment]
sure go ahead!

**Comment by AmanR28** [comment]
#15 Here it is.
