### ISSUE TITLE
Create a new component for searching comics.

### ISSUE THREAD

**Issue by himanshu272** [NJACKWinterOfCode/marvelUniverse#9]

**Comment by rajkumaar23** [comment]
Assign me this ? I would like to work on it. @sudipt1999

**Comment by sudipt1999** [comment]
Sure! Go ahead

**Comment by rajkumaar23** [comment]
Which is the end point for getting movies ?

**Comment by sudipt1999** [comment]
@rajkumaar23 I see there is no end point for movies so lets move with comics!
https://developer.marvel.com/docs
